### ISSUE TITLE
panic: runtime error: slice bounds out of range in readCustomAtom

### ISSUE THREAD

**Issue by gy741** [dhowden/tag#31]
Hello.

I found a slice bounds out of range bug in tag.

Please confirm.

Thanks.

reproduce code:

```
package tag

import (
	"strings"
	"testing"
)

func TestFuzzCrashers(t *testing.T) {

	var crashers = []string{
		"0000meta00\x00\b\xda\xca\x15\x1fmeta" +
		"\x00ETCO\x00\x00\xcameta\u007f\x00\x00\b\x00\x00\x02\xca" +
		"----\x00\x00\x00\bname",
	}

	for _, f := range crashers {
		ReadAtoms(strings.NewReader(f))
	}
}
```

Log

```
--- FAIL: TestFuzzCrashers (0.00s)
panic: runtime error: slice bounds out of range [recovered]
	panic: runtime error: slice bounds out of range

goroutine 5 [running]:
testing.tRunner.func1(0xc42004ec30)
	/usr/lib/go-1.8/src/testing/testing.go:622 +0x29d
panic(0x5379a0, 0x605120)
	/usr/lib/go-1.8/src/runtime/panic.go:489 +0x2cf
github.com/dhowden/tag.readCustomAtom(0x5f5f20, 0xc42000ae00, 0xc4000002c2, 0x4, 0x6284e0, 0x0, 0x0, 0x4)
	/home/karas/go/src/github.com/dhowden/tag/mp4.go:223 +0x575
github.com/dhowden/tag.metadataMP4.readAtoms(0x0, 0x0, 0xc420014cf0, 0x5f5f20, 0xc42000ae00, 0x4, 0x0)
	/home/karas/go/src/github.com/dhowden/tag/mp4.go:105 +0x274
github.com/dhowden/tag.metadataMP4.readAtoms(0x0, 0x0, 0xc420014cf0, 0x5f5f20, 0xc42000ae00, 0x4, 0x0)
	/home/karas/go/src/github.com/dhowden/tag/mp4.go:100 +0x3b4
github.com/dhowden/tag.metadataMP4.readAtoms(0x0, 0x0, 0xc420014cf0, 0x5f5f20, 0xc42000ae00, 0x4, 0x0)
	/home/karas/go/src/github.com/dhowden/tag/mp4.go:100 +0x3b4
github.com/dhowden/tag.metadataMP4.readAtoms(0x0, 0x0, 0xc420014cf0, 0x5f5f20, 0xc42000ae00, 0x0, 0x0)
	/home/karas/go/src/github.com/dhowden/tag/mp4.go:100 +0x3b4
github.com/dhowden/tag.ReadAtoms(0x5f5f20, 0xc42000ae00, 0xffffffee, 0x1000, 0xc420027f78, 0x4544c3)
	/home/karas/go/src/github.com/dhowden/tag/mp4.go:76 +0x88
github.com/dhowden/tag.TestFuzzCrashers(0xc42004ec30)
	/home/karas/go/src/github.com/dhowden/tag/fuzz_test.go:17 +0xbf
testing.tRunner(0xc42004ec30, 0x568cf8)
	/usr/lib/go-1.8/src/testing/testing.go:657 +0x96
created by testing.(*T).Run
	/usr/lib/go-1.8/src/testing/testing.go:697 +0x2ca
exit status 2
FAIL	github.com/dhowden/tag	0.006s
```

=================
[Acknowledgement]
This work was supported by ICT R&D program of MSIP/IITP. [R7518-16-1001, Innovation hub for high Performance Computing]

**Comment by dhowden** [comment]
Hi!  Thanks for the report.  I suspect there will be quite a few of these, I haven't tried to do any fuzzy-based testing on this repo yet.

**Comment by gy741** [comment]
Hello,

With go-fuzz, you can easily find the bug. 

Thanks.
